### ISSUE TITLE
Rename to MarkdownDoclet

### ISSUE THREAD

**Issue by Abnaxos** [Abnaxos/markdown-doclet#79]
Pegdown is deprecated. Rename the doclet to MarkdownDoclet (package ch.raffael.mddoclet). See also #76.

**Comment by pauxus** [comment]
Isn't that fixed by af97ade7e7bee55106e8ed5989c53f1025405b02? Also, any chance of you doing a prerelease of 1.4? With the new coordinates and especially the fixes provided by @loddar ?

**Comment by Abnaxos** [comment]
Sorry, yeah, it was fixed then. In master, but no release.

Now, I still have to do an update of the old IDEA that shows a bubble message that tells people to install the new plugin. It's getting a bit too late for that, too, though.

In case you didn't notice, 1.4 is released now.

**Comment by matozoid** [comment]
The README links to the intellij pegdown plugin, I guess you want to update that too?

**Comment by Abnaxos** [comment]
Thanks.
